### ISSUE TITLE
list.remove(x): x not in list

### ISSUE THREAD

**Issue by lewisporter** [joxeankoret/diaphora#118]
I was importing functions and I got this error:

```Traceback (most recent call last):
  File "/Applications/IDA Pro 7.1/ida.app/Contents/MacOS/python/ida_kernwin.py", line 7780, in activate
    self.control.OnCommand(idx, self.cmd.cmd_id)
  File "/Users/lewis.porter/git/diaphora/diaphora_ida.py", line 258, in OnCommand
    self.bindiff.import_selected(self.items, self.selected_items, cmd_id == self.cmd_import_selected_auto)
  File "/Users/lewis.porter/git/diaphora/diaphora_ida.py", line 1155, in import_selected
    self.import_items(new_items)
  File "/Users/lewis.porter/git/diaphora/diaphora_ida.py", line 1171, in import_items
    new_func = self.read_function(ea)
  File "/Users/lewis.porter/git/diaphora/diaphora_ida.py", line 1605, in read_function
    keys.remove(f - image_base)
ValueError: list.remove(x): x not in list```


Not sure why this happened. I stuck a Try-Except around line 1605 to find some more info should it happen again

**Comment by joxeankoret** [comment]
It's odd, I cannot make sense of it. Have you been able to re-reproduce?

**Comment by joxeankoret** [comment]
Closing for now. Please re-open if you experience it again.
