### ISSUE TITLE
Exception thrown when trying to show assembly

### ISSUE THREAD

**Issue by forker11234** [joxeankoret/diaphora#148]
Under tabs "Unmatched in primary" and "Unmatched in secondary" when clicking on "Show assembly" in some function it throws this exception:
```Traceback (most recent call last):
  File "C:\Program Files\IDA 7.2\python\ida_kernwin.py", line 7942, in activate
    self.control.OnCommand(idx, self.cmd.cmd_id)
  File "D:/Diaphora\diaphora_ida.py", line 257, in OnCommand
    elif cmd_id == self.cmd_import_selected or cmd_id == self.cmd_import_selected_auto:
  File "C:\Program Files\IDA 7.2\python\ida_kernwin.py", line 8141, in __getattr__
    raise AttributeError(attr)
AttributeError: cmd_import_selected_auto

**Comment by joxeankoret** [comment]
Please re-try with latest, I fixed this bug recently: 40535557749e7a3f8317567977088f821b836323
