### ISSUE TITLE
Error creating DB for ntoskrnl.exe 19645

### ISSUE THREAD

**Issue by yardenshafir** [joxeankoret/diaphora#187]
When attempting to create DB for ntoskrnl.exe version 19645 script crashes with error:

```Error: 'utf-8' codec can't decode byte 0xc8 in position 184: invalid continuation byte
Traceback (most recent call last):
  File "C:/Program Files/IDA Pro 7.4/diaphora-master\diaphora_ida.py", line 2284, in _diff_or_export
    bd.export()
  File "C:/Program Files/IDA Pro 7.4/diaphora-master\diaphora_ida.py", line 836, in export
    self.do_export(crashed_before)
  File "C:/Program Files/IDA Pro 7.4/diaphora-master\diaphora_ida.py", line 812, in do_export
    self.export_structures()
  File "C:/Program Files/IDA Pro 7.4/diaphora-master\diaphora_ida.py", line 2051, in export_structures
    definition = self.GetLocalType(i+1, PRTYPE_MULTI | PRTYPE_TYPE | PRTYPE_SEMI | PRTYPE_PRAGMA)
  File "C:/Program Files/IDA Pro 7.4/diaphora-master\diaphora_ida.py", line 2036, in GetLocalType
    return idc_print_type(stype, fields, name, flags)
  File "C:\Program Files\IDA Pro 7.4\python\3\ida_typeinf.py", line 7826, in idc_print_type
    return _ida_typeinf.idc_print_type(*args)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 184: invalid continuation byte```

**Comment by joxeankoret** [comment]
Weird. Let me try to reproduce it...

**Comment by joxeankoret** [comment]
I cannot reproduce the crash with IDA 7.5 Linux + ntoskrnl.exe 19645, but I suspect it's because of some struct/enum name that you have. Can you please run this script to see if it crashes for you?

```python
import idc

def DiaphoraGetLocalType(ordinal, flags):
  ret = get_local_tinfo(ordinal)
  if ret is not None:
    (stype, fields) = ret
    if stype:
      name = idc.get_numbered_type_name(ordinal)
      try:
        return idc_print_type(stype, fields, name, flags)
      except:
        print("Error: %s" % str(sys.exc_info()[1]))
        return ""
  return ""

local_types = idc.get_ordinal_qty()
print("Local types?", local_types)
if (local_types & 0x80000000) != 0:
  print("warning: get_ordinal_qty returned a negative number (0x%x)!" % local_types)

for i in range(local_types):
  name = idc.get_numbered_type_name(i+1)
  definition = DiaphoraGetLocalType(i+1, PRTYPE_MULTI | PRTYPE_TYPE | PRTYPE_SEMI | PRTYPE_PRAGMA)
  print("Def", definition)
```

**Comment by yardenshafir** [comment]
Oh, this was on IDA 7.4 on Windows. Maybe it's in IDA bug that was fixed in 7.5.

**Comment by joxeankoret** [comment]
I've just pushed a commit (https://github.com/joxeankoret/diaphora/commit/57b054de2b641d261fb1d00b00116054e6e60cfc) that should workaround your problem. Could you please verify?

**Comment by yardenshafir** [comment]
It works with the fix :)
Thank you!
