### ISSUE TITLE
diaphora.py: DLL load failed

### ISSUE THREAD

**Issue by Chrys4lisfag** [joxeankoret/diaphora#208]
C:\Users\\Desktop\diaphora-master\diaphora.py: DLL load failed: module not found.
Traceback (most recent call last):
  File "C:\Users\\Desktop\IDA Pro 7.5 SP3\python\3\ida_idaapi.py", line 616, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Users//Desktop/diaphora-master/diaphora.py", line 2150, in <module>
    exec(compile(open(script, "rb").read(), script, 'exec'))
  File "C:/Users/koval//diaphora-master\diaphora_ida.py", line 48, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: DLL load failed: module not found.

Py 3.7 installed pyqt5 as well

**Comment by joxeankoret** [comment]
This sounds rather odd. Have you tried running idapyswitch? Also, please do not install IDA in directories with spaces, or you will see errors that doesn't make any sense.

**Comment by Chrys4lisfag** [comment]
idapyswitch helped. It so strange, cuz IDA was already saying it loaded py 3.7

**Comment by joxeankoret** [comment]
It happens some times, no idea why :shrug:
