### ISSUE TITLE
IDA 8.0/Python 3.10: ValueError

### ISSUE THREAD

**Issue by kwargsorg** [joxeankoret/diaphora#241]
I've been consistently getting the following error with the latest build of Diaphora on IDA 8.0 for Linux with Python 3.10 when trying to produce a database for a file (and before diffing).

Error: Exceeds the limit (4300) for integer string conversion
Traceback (most recent call last):
  File "/home/jpm/source/diaphora/diaphora_ida.py", line 2520, in _diff_or_export
    bd.export()
  File "/home/jpm/source/diaphora/diaphora_ida.py", line 868, in export
    self.do_export(crashed_before)
  File "/home/jpm/source/diaphora/diaphora_ida.py", line 823, in do_export
    props = self.read_function(func)
  File "/home/jpm/source/diaphora/diaphora_ida.py", line 2015, in read_function
    pseudocode_primes = str(self.pseudo_hash[f])

I recently upgraded Python from 3.9 to 3.10 which is the only significant change to my environment I can think of recently.

**Comment by joxeankoret** [comment]
>Error: Exceeds the limit (4300) for integer string conversion
This is the very first time I see this error. Could you please share a sample?

**Comment by kwargsorg** [comment]
[sample.zip](https://github.com/joxeankoret/diaphora/files/10043502/sample.zip)

The password is "infected. It's malware so be careful!

**Comment by Myles1** [comment]
I've run into the same issue. It can be resolved by adding this:
```
if hasattr(sys, "set_int_max_str_digits"):
    sys.set_int_max_str_digits(0)
```

I created a PR with that change here: https://github.com/joxeankoret/diaphora/pull/242

**Comment by joxeankoret** [comment]
@kwargsorg I cannot reproduce it in Linux with IDA 8.0 or 8.1 and (a fresh installation of) Python 3.9 or 3.10 with the provided sample. Are you sure the sample you provided is the one triggering this error?

**Comment by kwargsorg** [comment]
[sample2.zip](https://github.com/joxeankoret/diaphora/files/10056668/sample2.zip)

Here is another sample (64-bit) that triggers the same exception for me. I've also included the sqlite file that does get created. There is also a 0 byte sqlite crash file that is created.

**Comment by joxeankoret** [comment]
I can reproduce it, thank you! I will be fixing it soon.
