### ISSUE TITLE
Could not find style module 'default', though it should be builtin

### ISSUE THREAD

**Issue by udunadan** [joxeankoret/diaphora#262]
This happens when I try to show diff in assembly, decompiler or see a patch.

Python version 3.11.4.

```python
Traceback (most recent call last):
  File "C:/Users/udunadan/Work/diaphora\diaphora_ida.py", line 305, in activate
    return self.obj.OnCommand(sel, self.cmd_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/udunadan/Work/diaphora\diaphora_ida.py", line 512, in OnCommand
    self.bindiff.show_pseudo_diff(self.items[n], html=False)
  File "C:/Users/udunadan/Work/diaphora\diaphora_ida.py", line 1591, in show_pseudo_diff
    res = self.generate_pseudo_diff(item[1], item[3], html=html, error_func=warning)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/udunadan/Work/diaphora\diaphora_ida.py", line 1566, in generate_pseudo_diff
    fmt = HtmlFormatter()
          ^^^^^^^^^^^^^^^
  File "C:\Users/udunadan/Work/diaphora-3.0\pygments\formatters\html.py", line 413, in __init__
  File "C:\Users/udunadan/Work/diaphora-3.0\pygments\formatter.py", line 66, in __init__
  File "C:\Users/udunadan/Work/diaphora-3.0\pygments\formatter.py", line 21, in _lookup_style
  File "C:\Users/udunadan/Work/diaphora-3.0\pygments\styles\__init__.py", line 84, in get_style_by_name
pygments.util.ClassNotFound: Could not find style module 'default', though it should be builtin.
```

**Comment by joxeankoret** [comment]
Hi!

I'm unable to reproduce it neither in Windows nor in Linux with neither Python 3.10.5 nor with 3.11.4. Can you please try the following to see if the problem goes away?

- Verify that you don't have pygments installed. Perhaps this is why it's triggering this error.
- Try with another Python version (like IDA's supplied 3.10.5 version).
