### ISSUE TITLE
TypeError: in method `'treeloc_t_itp_set'`, argument 2 of type `'item_preciser_t'`

### ISSUE THREAD

**Issue by enovella** [joxeankoret/diaphora#269]
# Issue
While diffing two binaries, there is a repetitive Python exception thrown. Unsure how this affects to the diffing
```sh
[Diaphora: Thu Sep 14 16:25:15 2023] Error importing item: in method 'treeloc_t_itp_set', argument 2 of type 'item_preciser_t'
Traceback (most recent call last):
  File "~/diaphora-3.1\diaphora_ida.py", line 2043, in import_instruction_level
    self.do_import_instruction_level_item(
  File "~/diaphora-3.1\diaphora_ida.py", line 1957, in do_import_instruction_level_item
    self.import_instruction(matched_syms[ea2], import_syms[ea1])
  File "~/diaphora-3.1\diaphora_ida.py", line 1847, in import_instruction
    tl.itp = mitp
TypeError: in method 'treeloc_t_itp_set', argument 2 of type 'item_preciser_t'
```

# Sample

FYI - They use the same SDK but they are not the same app with different version.
[samples.zip](https://github.com/joxeankoret/diaphora/files/12619358/samples.zip)

**Comment by joxeankoret** [comment]
I'm trying to reproduce it today. Hopefully I can get it fixed today too.

**Comment by joxeankoret** [comment]
And fixed, thanks for reporting! Feel free to reopen if you experience it again.
