### ISSUE TITLE
crash in ida8.3

### ISSUE THREAD

**Issue by zh913457894** [joxeankoret/diaphora#288]
I use diaphora under ida8.3.
diaphora version 3.1.1. 
I want to export ida database to sqlite, settings are all default options,only the 'to address' option has been modified.
I tried it twice and got the same crash

The crash log is as follows：
```[Diaphora: Thu Nov 30 10:14:42 2023] Error: list.remove(x): x not in list
Traceback (most recent call last):
  File "D:/gihub/diaphora-master-3.11/diaphora-master\diaphora_ida.py", line 1250, in export
    self.do_export(crashed_before)
  File "D:/gihub/diaphora-master-3.11/diaphora-master\diaphora_ida.py", line 1195, in do_export
    props = self.read_function(func)
  File "D:/gihub/diaphora-master-3.11/diaphora-master\diaphora_ida.py", line 2989, in read_function
    asm, assembly_addrs = self.extract_function_assembly_features(
  File "D:/gihub/diaphora-master-3.11/diaphora-master\diaphora_ida.py", line 2615, in extract_function_assembly_features
    keys.remove(base)
ValueError: list.remove(x): x not in list
[Diaphora: Thu Nov 30 10:14:42 2023] Removing crash file D:\img\XXXXXN002.2244B\sox.bin.sqlite-crash....
```

**Comment by joxeankoret** [comment]
I believe I have fixed it. Feel free to reopen if you hit it again.
