### ISSUE TITLE
AttributeError: 'CIDABinDiff' object has no attribute 'delete_function'

### ISSUE THREAD

**Issue by overfl0** [joxeankoret/diaphora#291]
While importing files using the "import all" or "import selected" menu option, I got this error.

```
Traceback (most recent call last):
  File "diaphora\diaphora_ida.py", line 305, in activate
    return self.obj.OnCommand(sel, self.cmd_id)
  File "diaphora\diaphora_ida.py", line 496, in OnCommand
    self.bindiff.import_one(self.items[n])
  File "diaphora\diaphora_ida.py", line 1483, in import_one
    self.delete_function(ea1)
AttributeError: 'CIDABinDiff' object has no attribute 'delete_function'
```

By quickly skimming over the code, it looks like that function was indeed present some time ago, but was then removed, while some references to it were kept.

At this moment, I can see two references to it:
- https://github.com/joxeankoret/diaphora/blob/7e46f6fbc3da418e2ce6f847c5ac930af8cb96bb/diaphora_ida.py#L1483 
- https://github.com/joxeankoret/diaphora/blob/7e46f6fbc3da418e2ce6f847c5ac930af8cb96bb/diaphora_ida.py#L2149

**Comment by joxeankoret** [comment]
Thank you very much for reporting! Fixed with 59017c5
