### ISSUE TITLE
AttributeError: module 'idc' has no attribute 'get_ordinal_qty'

### ISSUE THREAD

**Issue by How2Rev** [joxeankoret/diaphora#310]
got this error on IDA 9.0 beta when exporting a file 

```python
Traceback (most recent call last):
  File "C:\Users\titip\Desktop\secu\diaphora-3.2.1\diaphora_ida.py", line 1281, in export
    self.do_export(crashed_before)
  File "C:\Users\titip\Desktop\secu\diaphora-3.2.1\diaphora_ida.py", line 1248, in do_export
    self.export_structures()
  File "C:\Users\titip\Desktop\secu\diaphora-3.2.1\diaphora_ida.py", line 3329, in export_structures
    local_types = idc.get_ordinal_qty()
  File "C:\Users\titip\Desktop\secu\IDA9.0\python\3\ida_ida.py", line 4612, in __getattribute__
    return getattr(self.orig, name)
AttributeError: module 'idc' has no attribute 'get_ordinal_qty'
```

This function was deleted from hexrays API in IDA 9.0 (no equivalence)
edit: saw you fixed this issues, didn't git pull

**Comment by joxeankoret** [comment]
Lol, no worries :)

**Comment by gyyr7283-ops** [comment]
If someone could solve it ,please tell me, thanks
