### ISSUE TITLE
IndexError: list index out of range (executing prime = str(self.primes[cc]))

### ISSUE THREAD

**Issue by joxeankoret** [joxeankoret/diaphora#37]
A trace similar to the following one is generated when exporting:

```
Error: list index out of range
Traceback (most recent call last):
File "C:/Users/user/Desktop/diaphora-master/diaphora-master/diaphora.py", line 3694, in _diff_or_export
  bd.export()
File "C:/Users/user/Desktop/diaphora-master/diaphora-master/diaphora.py", line 1506, in export
  self.do_export()
File "C:/Users/user/Desktop/diaphora-master/diaphora-master/diaphora.py", line 1482, in do_export
  props = self.read_function(func)
File "C:/Users/user/Desktop/diaphora-master/diaphora-master/diaphora.py", line 1255, in read_function
  prime = str(self.primes[cc])
IndexError: list index out of range
```

**Comment by joxeankoret** [comment]
Fixed
