### ISSUE TITLE
fault export idb 2 sql

### ISSUE THREAD

**Issue by flyninja** [joxeankoret/diaphora#49]
module: jscript.dll x32-86 MS015-112
IDA: 6.6.141224
OS: win8.1 x64
stacktrace:
```
Error: expected string or Unicode object, NoneType found
Traceback (most recent call last):
  File "C:/diaphora/diaphora.py", line 3726, in _diff_or_export
    bd.export()
  File "C:/diaphora/diaphora.py", line 1530, in export
    self.do_export()
  File "C:/diaphora/diaphora.py", line 1524, in do_export
    self.export_structures()
  File "C:/diaphora/diaphora.py", line 1461, in export_structures
    self.add_program_data(type_name, name, definition)
  File "C:/diaphora/diaphora.py", line 1050, in add_program_data
    cur.execute(sql, values)
TypeError: expected string or Unicode object, NoneType found
```

**Comment by flyninja** [comment]
Sorry, duplicate #40.

**Comment by joxeankoret** [comment]
No worries.
