### ISSUE TITLE
Transaction errors?

### ISSUE THREAD

**Issue by ionescu007** [joxeankoret/diaphora#61]
Error: cannot rollback - no transaction is active
Traceback (most recent call last):
  File "C:/Program Files (x86)/IDA 6.95/plugins/diaphora-master/diaphora.py", line 3885, in _diff_or_export
    bd.export()
  File "C:/Program Files (x86)/IDA 6.95/plugins/diaphora-master/diaphora.py", line 1623, in export
    self.do_export()
  File "C:/Program Files (x86)/IDA 6.95/plugins/diaphora-master/diaphora.py", line 1613, in do_export
    db.execute("BEGIN transaction")
OperationalError: cannot rollback - no transaction is active

Any ideas? This is using the latest master.

**Comment by fuzun** [comment]
Maybe it needs sql drivers?

**Comment by joxeankoret** [comment]
No, it has nothing to do with SQL Drivers @fuzun. @ionescu007, number of functions in the database?

**Comment by joxeankoret** [comment]
"Officially" fixed with 119f6294d6950722a5d8f2c3a31654a98e18c566.
